name: 'OCR Bot'
description: 'Extracts keywords from images in issue bodies'
branding:
  icon: "align-center"
  color: "yellow"
inputs:
  GITHUB_TOKEN:
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
